[package]
name = "packet"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.94"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
linkme = "0.3.32"
tokio = { workspace = true }
flate2 = "1.1.0"
log = "0.4.26"
